vsim work.mac_controller
add wave -position end  sim:/mac_controller/clk
add wave -position end  sim:/mac_controller/a00
add wave -position end  sim:/mac_controller/a01
add wave -position end  sim:/mac_controller/a02
add wave -position end  sim:/mac_controller/a10
add wave -position end  sim:/mac_controller/a11
add wave -position end  sim:/mac_controller/a12
add wave -position end  sim:/mac_controller/a20
add wave -position end  sim:/mac_controller/a21
add wave -position end  sim:/mac_controller/a22
add wave -position end  sim:/mac_controller/b00
add wave -position end  sim:/mac_controller/b01
add wave -position end  sim:/mac_controller/b02
add wave -position end  sim:/mac_controller/b10
add wave -position end  sim:/mac_controller/b11
add wave -position end  sim:/mac_controller/b12
add wave -position end  sim:/mac_controller/b20
add wave -position end  sim:/mac_controller/b21
add wave -position end  sim:/mac_controller/b22
add wave -position end  sim:/mac_controller/o00
add wave -position end  sim:/mac_controller/o01
add wave -position end  sim:/mac_controller/o02
add wave -position end  sim:/mac_controller/o10
add wave -position end  sim:/mac_controller/o11
add wave -position end  sim:/mac_controller/o12
add wave -position end  sim:/mac_controller/o20
add wave -position end  sim:/mac_controller/o21
add wave -position end  sim:/mac_controller/o22
add wave -position end  sim:/mac_controller/tv00
add wave -position end  sim:/mac_controller/tv01
add wave -position end  sim:/mac_controller/tv02
add wave -position end  sim:/mac_controller/tv10
add wave -position end  sim:/mac_controller/tv11
add wave -position end  sim:/mac_controller/tv12
add wave -position end  sim:/mac_controller/tv20
add wave -position end  sim:/mac_controller/tv21
add wave -position end  sim:/mac_controller/tv22
add wave -position end  sim:/mac_controller/v00
add wave -position end  sim:/mac_controller/v01
add wave -position end  sim:/mac_controller/v02
add wave -position end  sim:/mac_controller/v10
add wave -position end  sim:/mac_controller/v11
add wave -position end  sim:/mac_controller/v12
add wave -position end  sim:/mac_controller/v20
add wave -position end  sim:/mac_controller/v21
add wave -position end  sim:/mac_controller/v22
add wave -position end  sim:/mac_controller/iA00
add wave -position end  sim:/mac_controller/iA01
add wave -position end  sim:/mac_controller/iA02
add wave -position end  sim:/mac_controller/iA10
add wave -position end  sim:/mac_controller/iA11
add wave -position end  sim:/mac_controller/iA12
add wave -position end  sim:/mac_controller/iA20
add wave -position end  sim:/mac_controller/iA21
add wave -position end  sim:/mac_controller/iA22
add wave -position end  sim:/mac_controller/iB00
add wave -position end  sim:/mac_controller/iB01
add wave -position end  sim:/mac_controller/iB02
add wave -position end  sim:/mac_controller/iB10
add wave -position end  sim:/mac_controller/iB11
add wave -position end  sim:/mac_controller/iB12
add wave -position end  sim:/mac_controller/iB20
add wave -position end  sim:/mac_controller/iB21
add wave -position end  sim:/mac_controller/iB22
add wave -position end  sim:/mac_controller/state
add wave -position end  sim:/mac_controller/st
add wave -position end  sim:/mac_controller/ready
force clk 0 0 ns, 1 2 ns -repeat 4 ns
force a00 8'b00110000 0 ns 		 
force a01 8'b00000000 0 ns		
force a02 8'b01001000 0 ns  		
force a10 8'b00110000 0 ns   		
force a11 8'b00100000 0 ns		
force a12 8'b01000000 0 ns  		
force a20 8'b01001000 0 ns 		
force a21 8'b01000000 0 ns		
force a22 8'b01000100 0 ns  		
force b00 8'b01000000 0 ns 		
force b01 8'b00110000 0 ns
force b02 8'b00110000 0 ns 		
force b10 8'b00111000 0 ns		
force b11 8'b01000000 0 ns 		
force b12 8'b01000000 0 ns		
force b20 8'b01000000 0 ns 		
force b21 8'b00100000 0 ns		
force b22 8'b00000000 0 ns 	
run